import type { ResolvedBrand } from '../resolver.js';
import type { Emitter } from './types.js';

const slug = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');

const swatchValue = (brand: ResolvedBrand, swatchId: string): string => {
  const sw = brand.palette.data.swatches.find((s) => s.id === swatchId);
  return sw?.value ?? '#000000';
};

const emitVars = (lines: string[], indent = '  ') => lines.map((l) => `${indent}${l}`).join('\n');

export const cssEmitter: Emitter = {
  name: 'css',
  description: 'CSS custom properties (:root + prefers-color-scheme dark)',

  emit(brand) {
    const swatchLines = brand.palette.data.swatches.map(
      (s) => `--color-swatch-${slug(s.id)}: ${s.value};`,
    );

    const lightRoleLines = Object.entries(brand.palette.data.modes.light.roles).map(
      ([role, swatchId]) => `--color-${slug(role)}: ${swatchValue(brand, swatchId)};`,
    );
    const darkRoleLines = Object.entries(brand.palette.data.modes.dark.roles).map(
      ([role, swatchId]) => `--color-${slug(role)}: ${swatchValue(brand, swatchId)};`,
    );

    const brandRoleLines = brand.roles?.colors
      ? Object.entries(brand.roles.colors).map(
          ([role, swatchId]) => `--brand-color-${slug(role)}: ${swatchValue(brand, swatchId)};`,
        )
      : [];

    const fontLines: string[] = [];
    for (const font of brand.fonts) {
      const stack = [font.data.family, ...font.data.fallbackStack]
        .map((f) => (f.includes(' ') ? `'${f}'` : f))
        .join(', ');
      fontLines.push(`--font-${slug(font.role)}: ${stack};`);
    }

    const header = `/*
 * ${brand.name} (${brand.id}@${brand.version})
 * Palette: ${brand.palette.slug}@${brand.palette.resolvedVersion}
 * Fonts:   ${brand.fonts.map((f) => `${f.role}=${f.slug}@${f.resolvedVersion}`).join(', ')}
 * Generated by brand-atoms converter — do not edit by hand.
 */`;

    const contents = `${header}

:root {
  /* Swatches (source-of-truth color values) */
${emitVars(swatchLines)}

  /* Light-mode semantic roles */
${emitVars(lightRoleLines)}
${brandRoleLines.length > 0 ? `\n  /* Brand-level role overrides */\n${emitVars(brandRoleLines)}\n` : ''}
  /* Typography */
${emitVars(fontLines)}
}

@media (prefers-color-scheme: dark) {
  :root {
    /* Dark-mode semantic roles override light-mode values */
${emitVars(darkRoleLines, '    ')}
  }
}
`;

    return [{ path: 'css/tokens.css', contents }];
  },
};
