import type { ResolvedBrand } from '../resolver.js';
import type { Emitter } from './types.js';

const kotlinIdent = (s: string): string => {
  const camel = s
    .toLowerCase()
    .replace(/[^a-z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-z0-9]/gi, '');
  if (!camel) return 'unnamed';
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const hexToCompose = (hex: string): string => {
  const normalized = hex.replace('#', '').toUpperCase();
  if (normalized.length === 6) return `Color(0xFF${normalized})`;
  if (normalized.length === 8) {
    return `Color(0x${normalized.slice(6, 8)}${normalized.slice(0, 6)})`;
  }
  return 'Color(0xFF000000)';
};

export const kotlinEmitter: Emitter = {
  name: 'kotlin',
  description: 'Jetpack Compose Color tokens (Kotlin)',

  emit(brand) {
    const lines: string[] = [];
    const header = `/*
 * ${brand.name} (${brand.id}@${brand.version})
 * Palette: ${brand.palette.slug}@${brand.palette.resolvedVersion}
 * Fonts:   ${brand.fonts.map((f) => `${f.role}=${f.slug}@${f.resolvedVersion}`).join(', ')}
 * Generated by brand-atoms converter — do not edit by hand.
 */

package com.brandatoms.${brand.id.replace(/[^a-z0-9]/gi, '')}

import androidx.compose.ui.graphics.Color
`;
    lines.push(header);

    lines.push('/** Source-of-truth color swatches. */');
    lines.push('object BrandSwatch {');
    for (const s of brand.palette.data.swatches) {
      lines.push(`    /** ${s.name}${s.description ? ` — ${s.description}` : ''} */`);
      lines.push(`    val ${kotlinIdent(s.id)} = ${hexToCompose(s.value)}`);
    }
    lines.push('}');
    lines.push('');

    lines.push('/** Semantic color roles for light mode. */');
    lines.push('object BrandLight {');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.light.roles)) {
      lines.push(`    val ${kotlinIdent(role)} = BrandSwatch.${kotlinIdent(swatchId)}`);
    }
    lines.push('}');
    lines.push('');

    lines.push('/** Semantic color roles for dark mode. */');
    lines.push('object BrandDark {');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.dark.roles)) {
      lines.push(`    val ${kotlinIdent(role)} = BrandSwatch.${kotlinIdent(swatchId)}`);
    }
    lines.push('}');
    lines.push('');

    if (brand.roles?.colors) {
      lines.push('/** Brand-level color role overrides. */');
      lines.push('object BrandColor {');
      for (const [role, swatchId] of Object.entries(brand.roles.colors)) {
        lines.push(`    val ${kotlinIdent(role)} = BrandSwatch.${kotlinIdent(swatchId)}`);
      }
      lines.push('}');
      lines.push('');
    }

    lines.push('/** Typography family names by brand role. */');
    lines.push('object BrandFont {');
    for (const font of brand.fonts) {
      lines.push(`    /** ${font.data.name} (${font.slug}@${font.resolvedVersion}) */`);
      lines.push(`    const val ${kotlinIdent(font.role)} = "${font.data.family}"`);
    }
    lines.push('}');

    return [{ path: 'kotlin/BrandTokens.kt', contents: `${lines.join('\n')}\n` }];
  },
};
