import type { ResolvedBrand } from '../resolver.js';
import type { Emitter } from './types.js';

const slug = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');

const swatchValue = (brand: ResolvedBrand, swatchId: string): string => {
  const sw = brand.palette.data.swatches.find((s) => s.id === swatchId);
  return sw?.value ?? '#000000';
};

export const scssEmitter: Emitter = {
  name: 'scss',
  description: 'SCSS variables + Sass maps for swatches, roles, and fonts',

  emit(brand) {
    const lines: string[] = [];
    lines.push(`// ${brand.name} (${brand.id}@${brand.version})`);
    lines.push(`// Palette: ${brand.palette.slug}@${brand.palette.resolvedVersion}`);
    lines.push(
      `// Fonts:   ${brand.fonts.map((f) => `${f.role}=${f.slug}@${f.resolvedVersion}`).join(', ')}`,
    );
    lines.push('// Generated by brand-atoms converter — do not edit by hand.');
    lines.push('');

    lines.push('// ─── Swatches ─────────────────────────────────────────');
    for (const s of brand.palette.data.swatches) {
      lines.push(`$swatch-${slug(s.id)}: ${s.value};`);
    }
    lines.push('');

    lines.push('// ─── Light-mode role mappings ─────────────────────────');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.light.roles)) {
      lines.push(`$light-${slug(role)}: $swatch-${slug(swatchId)};`);
    }
    lines.push('');

    lines.push('// ─── Dark-mode role mappings ──────────────────────────');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.dark.roles)) {
      lines.push(`$dark-${slug(role)}: $swatch-${slug(swatchId)};`);
    }
    lines.push('');

    if (brand.roles?.colors) {
      lines.push('// ─── Brand-level color role overrides ─────────────────');
      for (const [role, swatchId] of Object.entries(brand.roles.colors)) {
        lines.push(`$brand-${slug(role)}: $swatch-${slug(swatchId)};`);
      }
      lines.push('');
    }

    lines.push('// ─── Typography ───────────────────────────────────────');
    for (const font of brand.fonts) {
      const stack = [font.data.family, ...font.data.fallbackStack]
        .map((f) => (f.includes(' ') ? `'${f}'` : f))
        .join(', ');
      lines.push(`$font-${slug(font.role)}: (${stack});`);
    }
    lines.push('');

    lines.push('// ─── Iteration maps ───────────────────────────────────');
    lines.push('$swatches: (');
    for (const s of brand.palette.data.swatches) {
      lines.push(`  "${s.id}": $swatch-${slug(s.id)},`);
    }
    lines.push(');');
    lines.push('');
    lines.push('$light-roles: (');
    for (const [role] of Object.entries(brand.palette.data.modes.light.roles)) {
      lines.push(`  "${role}": $light-${slug(role)},`);
    }
    lines.push(');');
    lines.push('');
    lines.push('$dark-roles: (');
    for (const [role] of Object.entries(brand.palette.data.modes.dark.roles)) {
      lines.push(`  "${role}": $dark-${slug(role)},`);
    }
    lines.push(');');

    return [{ path: 'scss/_tokens.scss', contents: `${lines.join('\n')}\n` }];
  },
};
