import type { ResolvedBrand } from '../resolver.js';
import type { Emitter } from './types.js';

const swiftIdent = (s: string): string => {
  const camel = s
    .toLowerCase()
    .replace(/[^a-z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-z0-9]/gi, '');
  return camel || 'unnamed';
};

const swatchValue = (brand: ResolvedBrand, swatchId: string): string => {
  const sw = brand.palette.data.swatches.find((s) => s.id === swatchId);
  return sw?.value ?? '#000000';
};

const hexToColorLiteral = (hex: string): string => {
  const normalized = hex.replace('#', '');
  const r = Number.parseInt(normalized.slice(0, 2), 16) / 255;
  const g = Number.parseInt(normalized.slice(2, 4), 16) / 255;
  const b = Number.parseInt(normalized.slice(4, 6), 16) / 255;
  const a = normalized.length === 8 ? Number.parseInt(normalized.slice(6, 8), 16) / 255 : 1.0;
  return `Color(.sRGB, red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, opacity: ${a.toFixed(4)})`;
};

export const swiftEmitter: Emitter = {
  name: 'swift',
  description: 'SwiftUI Color tokens (Swift 5.5+)',

  emit(brand) {
    const lines: string[] = [];
    const header = `//
// ${brand.name} (${brand.id}@${brand.version})
// Palette: ${brand.palette.slug}@${brand.palette.resolvedVersion}
// Fonts:   ${brand.fonts.map((f) => `${f.role}=${f.slug}@${f.resolvedVersion}`).join(', ')}
// Generated by brand-atoms converter — do not edit by hand.
//

import SwiftUI
`;
    lines.push(header);

    lines.push('/// Source-of-truth color swatches from the referenced palette.');
    lines.push('public enum BrandSwatch {');
    for (const s of brand.palette.data.swatches) {
      lines.push(`    /// ${s.name}${s.description ? ` — ${s.description}` : ''}`);
      lines.push(`    public static let ${swiftIdent(s.id)} = ${hexToColorLiteral(s.value)}`);
    }
    lines.push('}');
    lines.push('');

    lines.push('/// Semantic color roles for light mode.');
    lines.push('public enum BrandLight {');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.light.roles)) {
      lines.push(`    public static let ${swiftIdent(role)} = BrandSwatch.${swiftIdent(swatchId)}`);
    }
    lines.push('}');
    lines.push('');

    lines.push('/// Semantic color roles for dark mode.');
    lines.push('public enum BrandDark {');
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.dark.roles)) {
      lines.push(`    public static let ${swiftIdent(role)} = BrandSwatch.${swiftIdent(swatchId)}`);
    }
    lines.push('}');
    lines.push('');

    if (brand.roles?.colors) {
      lines.push('/// Brand-level color role overrides.');
      lines.push('public enum BrandColor {');
      for (const [role, swatchId] of Object.entries(brand.roles.colors)) {
        lines.push(
          `    public static let ${swiftIdent(role)} = BrandSwatch.${swiftIdent(swatchId)}`,
        );
      }
      lines.push('}');
      lines.push('');
    }

    lines.push('/// Typography family names by brand role.');
    lines.push('public enum BrandFont {');
    for (const font of brand.fonts) {
      lines.push(`    /// ${font.data.name} (${font.slug}@${font.resolvedVersion})`);
      lines.push(`    public static let ${swiftIdent(font.role)} = "${font.data.family}"`);
    }
    lines.push('}');

    return [{ path: 'swift/BrandTokens.swift', contents: `${lines.join('\n')}\n` }];
  },
};
