import type { ResolvedBrand } from '../resolver.js';
import type { Emitter } from './types.js';

const slug = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');

const swatchValue = (brand: ResolvedBrand, swatchId: string): string => {
  const sw = brand.palette.data.swatches.find((s) => s.id === swatchId);
  return sw?.value ?? '#000000';
};

export const tailwindEmitter: Emitter = {
  name: 'tailwind',
  description: 'Tailwind v3 theme config (theme.extend.colors, fontFamily)',

  emit(brand) {
    const swatches: Record<string, string> = {};
    for (const s of brand.palette.data.swatches) {
      swatches[slug(s.id)] = s.value;
    }

    const lightRoles: Record<string, string> = {};
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.light.roles)) {
      lightRoles[slug(role)] = swatchValue(brand, swatchId);
    }
    const darkRoles: Record<string, string> = {};
    for (const [role, swatchId] of Object.entries(brand.palette.data.modes.dark.roles)) {
      darkRoles[slug(role)] = swatchValue(brand, swatchId);
    }

    const brandRoles: Record<string, string> = {};
    if (brand.roles?.colors) {
      for (const [role, swatchId] of Object.entries(brand.roles.colors)) {
        brandRoles[slug(role)] = swatchValue(brand, swatchId);
      }
    }

    const fontFamily: Record<string, string[]> = {};
    for (const font of brand.fonts) {
      fontFamily[slug(font.role)] = [font.data.family, ...font.data.fallbackStack];
    }

    const config = {
      content: ['./src/**/*.{html,js,jsx,ts,tsx,astro,vue,svelte}'],
      theme: {
        extend: {
          colors: {
            swatch: swatches,
            'role-light': lightRoles,
            'role-dark': darkRoles,
            ...(Object.keys(brandRoles).length > 0 && { brand: brandRoles }),
          },
          fontFamily,
        },
      },
    };

    const header = `/**
 * ${brand.name} (${brand.id}@${brand.version})
 * Palette: ${brand.palette.slug}@${brand.palette.resolvedVersion}
 * Fonts:   ${brand.fonts.map((f) => `${f.role}=${f.slug}@${f.resolvedVersion}`).join(', ')}
 * Generated by brand-atoms converter — do not edit by hand.
 *
 * Usage (Tailwind v3):
 *   // tailwind.config.js
 *   const brand = require('./tailwind.config.cjs');
 *   module.exports = { ...brand, content: [...brand.content, 'your-own-globs'] };
 *
 * Then in your templates:
 *   class="bg-role-light-background text-role-light-text-primary"
 *   class="bg-swatch-nord8 text-brand-cta"
 *   class="font-heading"
 */
`;

    const contents = `${header}\nmodule.exports = ${JSON.stringify(config, null, 2)};\n`;

    return [{ path: 'tailwind/tailwind.config.cjs', contents }];
  },
};
